// Microsoft Sentinel (KQL). Sysmon EID 10 (ProcessAccess) into a 'Sysmon' table.
Sysmon
| where (TargetImage endswith "\\lsass.exe" and (GrantedAccess in~ ("0x1010", "0x1410", "0x1418", "0x1438", "0x143a", "0x147a", "0x1fffff"))) and (not(((SourceImage endswith "\\wininit.exe" or SourceImage endswith "\\csrss.exe" or SourceImage endswith "\\wmiprvse.exe" or SourceImage endswith "\\MsMpEng.exe") or SourceImage contains "\\Elastic\\Agent\\")))
